### ISSUE TITLE
Créer docker FeatCount

### ISSUE THREAD

**Issue by Sherman-1** [Sherman-1/Hackaton#1]

**Comment by soeurwiki** [comment]
### Problème
L'image se contrsuit correctement mais le PATH est à revoir
`export PATH=/subread-2.0.3-source/bin/featureCounts:$PATH
`
### Solution (à tester)
Retirer le fichier featureCounts du chemin, sinon on est situé un cran trop loin
`export PATH=/subread-2.0.3-source/bin:$PATH
`
