### ISSUE TITLE
Faire fonctionner un process avec Singularity

### ISSUE THREAD

**Issue by PlotosusLineatus** [Sherman-1/Hackaton#13]

**Comment by soeurwiki** [comment]
# Réunion 21/10/22
- Attention à préciser les **input** et **output** pour les _process_.
- C'est dans la balise workflow que l'on précisera les _process_ à exécuter (extract fastq, extract genome , concaténer les chromosomes).
## A faire

- [ ] Télécharger non pas le chromosome 3 uniquement, mais TOUS.
- [ ] Concaténer tous les chromosomes dans un fichier.
