### ISSUE TITLE
Container R/DESeq2

### ISSUE THREAD

**Issue by soeurwiki** [Sherman-1/Hackaton#16]
# Objectif
Construire un container avec les packages R nécessaires pour la pipeline.

### Problèmes
- Doit on ( peut-on ) installer les packages R dans le container Singularity.R ? ( je n’ai trouvé que de la docu sur une installation intra-container via des definition.file docker )
    - Je parviens à ouvrir le container en shell et lancer R, puis installer un package via la ligne de commande mais comment automatiser le processus ?

**Comment by soeurwiki** [comment]
## Réunion 21/10/22
**Pistes de résolutions :**
Il est possible de construire un container basé sur R, ensuite :
- Faire un script R avec les `install.packages ` et ensuite le container devra le _run_.
- Utiliser directement `R -e "install.packages ..."` qui permet de passer des commandes R directement dans le _script_.

**Comment by Sherman-1** [comment]
Container build correctement et contient DESeq. Reste maintenant à savoir l'intégrer dans le workflow en appelant un script particulier
