### ISSUE TITLE
Merge /containers avec un /workflow 

### ISSUE THREAD

**Issue by Sherman-1** [Sherman-1/Hackaton#17]
Repartir d'une branche qui possède un dossier containers et un dossier workflow de laquelle on tire des branches de dév pour ajouter/modifier des scripts ?

**Comment by soeurwiki** [comment]
Oui je pense, on peut créer les dossier dans le main et tirer la branche à partir de là.

Après on aura au pire autant de branches que d'étapes. Il faudra juste faire attention à ne pas créer trop de branches "inutiles".
Par exemple pour les containers, on aurait dû tirer une seule branche et faire nos scripts singularity/docker parce-qu'avoir eu une branche pour chaque container n'a pas été très pratique comme on ne voyait pas l'avancé des autres sur les containers déjà faits.

Je ne sais pas si c'est très clair, mais en tout cas, pour répondre à ta question deux dossiers de travail ça me parait bien !
