### ISSUE TITLE
Process Mapping/Index

### ISSUE THREAD

**Issue by soeurwiki** [Sherman-1/Hackaton#22]
## Etat actuel
Quand on run la pipeline, il y a un bug au process _samtoolsIndex_

![image](https://user-images.githubusercontent.com/55387021/199995084-15476f39-84c1-45da-ae1b-56b7ba5288d4.png)

La commande `samtools index ${bam}` ne fonctionne pas car le fichier (de sortie du process _mapping_) n'est pas correct apparemment...

### Recherche

- Si on lance la commande samtools dans le terminal : ça ne fonctionne pas, le fichier d'entrée n'est pas correct.
Ce n'est donc pas un problème d'écriture du process _samtoolsIndex_.
![image](https://user-images.githubusercontent.com/55387021/199999024-55d01f5b-2ef9-49f2-bfce-bb2504671407.png)

- Si on regarde le fichier de sortie du process _mapping_ : il est **VIDE** !

Il y a donc un problème en amont, dans le process _mapping_.

**Comment by soeurwiki** [comment]
### Le process _mapping_ :

La commande run est celle-ci : 
```
    STAR --outSAMstrandField intronMotif \
        --outFilterMismatchNmax 4 \
        --outFilterMultimapNmax 10 \
        --genomeDir ${index} \
        --readFilesIn <(gunzip -c ${r1}) <(gunzip -c ${r2}) \
        --runThreadN 4 \
        --outSAMunmapped None \
        --outSAMtype BAM SortedByCoordinate \
        --outStd BAM_SortedByCoordinate \
        --genomeLoad NoSharedMemory \
        --outFileNamePrefix ${srr} 
        > ${srr}.bam  
```
  ### Pistes de résolution 1 : 
Les fichiers d'entrée du process _mapping_ sont les fichiers fastq qui avaient été téléchargés : Il ne sont pas zippés !! Pas besoin des` gunzip -c` donc.

#### Résultat
C'est une bonne modification, mais le problème ne vient pas de là...

### Pistes de résolution 2

Tenter de faire passer cette fameuse commande STAR du process _mapping_ dans le terminal, jusqu'à obtention du bon fichier .bam ...

**Comment by soeurwiki** [comment]
## Commande STAR dans le terminal

Plutôt que de modifier indéfiniment le process nextflow, le but est de run la commande dans le terminal.
```
STAR  --outSAMstrandField intronMotif\
           --outFilterMismatchNmax 4 \
          --outFilterMultimapNmax 10  \
          --genomeDir ./results/genome_index/ref \
          --readFilesIn ./data/fastq/SRR628588_1.fastq  ./data/fastq/SRR628588_2.fastq  \
          --runThreadN 30\
          --outSAMunmapped None \
          --outSAMtype BAM SortedByCoordinate \
          --outStd BAM_SortedByCoordinate \
          --genomeLoad NoSharedMemory
          --outFileNamePrefix map_ \
           > MAP.bam 
```

- On prend donc les fichiers SRR628588_1.fastq et SRR628588_2.fastq, les préfixes des fichiers de sortie sera 'map_' mais ils seront tous concaténés dans MAP.bam

### Résultat

![image](https://user-images.githubusercontent.com/55387021/200001528-4f535c29-0e15-4739-9d5c-2dae40110043.png)

Il y a une erreur...pourtant j'ai tous les accès aux dossiers/fichiers et bien assez de place sur la VM....

### Pistes de résolution

Apparemment ce serait dû au nombre de coeur. Quand bien même la VM est capable de prendre dans mon cas, 32 coeurs, la version de STAR ne peut pas en prendre autant, il faut donc tester avec beaucoup moins. (c'est dû au nombre important de fichiers temporaires que STAR génère) -- https://github.com/alexdobin/STAR/issues/269

**Comment by soeurwiki** [comment]
## Hallelujah

J'ai testé avec 8 coeurs et \**roulement de tambours*\* ça marche ! En tout cas ça a l'air

### La commande STAR

Toujours la même que précédemment avec  ` --runThreadN 8`.
=> Pas de message d'erreur ! Les fichiers sont bien créés : 

![image](https://user-images.githubusercontent.com/55387021/200004666-d1ed746f-e5a9-49c7-bc7c-b381934a9090.png)

### La commande samtools

Du coup, on peut lancer la commande `samtools index MAP.bam` : ça fonctionne ! On a bien un fichier .bai (MAP.bam.bai) 🎉
 
(Et les fichiers bam comme bai ne sont pas vides)

## Suite

Il faut maintenant retester les process et voir si ça fonctionne...
Autrement dit, les changements à faire : 
- Ne pas mettre trop de coeur dans la commande STAR
- Enlever les `gunzip -c`
- Ajouter les fichiers output (il n'y a pas que des .bam en sortie)

**Comment by soeurwiki** [comment]
## Update

Toujours la même erreur...
![image](https://user-images.githubusercontent.com/55387021/200039164-36794072-8e86-4af0-88fc-b9541b3e3b59.png)

Cependant, je ne pense pas que la réflexion précédente était inutile, il s'agissait de problèmes auxquels nous aurions été confronté à un moment donné.

### Ce qui change

Quand la commande est lancé dans le terminal, ça fonctionne.
Dès que c'est dans le process, il y a un problème dans la construction du fichier .bam (process mapping).

-> Il ne fait pas du tout la même taille que celui qu'on obtient via une commande manuelle :
**Terminal** : SRR628588.bam 2208383176     **Nextflow** : SRR628588.bam 72

## Réflexions

- Puisque la commande STAR est exactement la même, la seule marge d'erreur possible doit provenir des inputs.
Dans le process, on a besoin de **index** (genomeDir) de **r1** et **r2** (readFilesIn) et **srr** (outFileNamePrefix)

### Vérifications
- **srr** : Il s'agit bien de SRR628588, les fichiers de sortie commencent bien par ça.
- **r1, r2** : Il s'agit bien de SRR628588_1.fastq et SRR628588_2.fastq (je les ai print pour voir)
![image](https://user-images.githubusercontent.com/55387021/200040738-5895f920-0b65-4991-bd5f-ccacad6bca19.png)

- **index** : Quand je le print, j'obtiens `ref` Alors que j'ai besoin de ` ./results/genome_index/ref` ❗ 

### Piste de résolution
Changer ce input index pour qu'il soit celui attendu.

-----

**Edit** : Alors c'est un gros fail je crois, puisque je viens de remarquer que même r1 et r2 ne seraient pas corrects puisqu'il ne faut pas seulement SRR628588_1.fastq  mais ./data/fastq/SRR628588_1.fastq dans la commande terminal...

- J'ai testé en modifiant seulement l'index, ça ne marche pas
- J'ai modifié l'index et r1, r2 ça ne marche pas.

Je sèche, je ne vois pas d'où viens l'erreur étant donné qu'elle ne provient pas des inputs (le process trouve les fichiers, c'est l'exécution qui se fait, et sans bug détecté alors qu'il y en a clairement un !!) 🥲

**Comment by PlotosusLineatus** [comment]
Il suffisait de mettre la commande STAR sur une unique ligne 😵‍💫 Ne pas mettre de \
