### ISSUE TITLE
Réorganisation globale du Git

### ISSUE THREAD

**Issue by Sherman-1** [Sherman-1/Hackaton#24]
Maintenant que tous nos containers fonctionnent, on devrait se faire un environnement de travail bien propre où le dossier container contient les images ( et pas les descriptions files ) et un dossier "description" contient les description files. Comme ça on irait chercher toutes nos images au même endroit

**Comment by Sherman-1** [comment]
Je propose que chacun garde ce qui est essentiel au déroulement de ses parties ( ce qu'on avait partagé dans notions ), pas de fichiers tests ou de dir temporaires, puis on fuse tout dans la branche Dev de laquelle on repart de PLUS BELLE pour la suite du projet

**Comment by soeurwiki** [comment]
Attention par contre à surtout pas mettre les images sur Git. On se crée le dossier en local, avec le même nom pour faciliter l'écriture des codes ( peut-être ajouter un petit script à lancer qui va créer les images et les mettre dans un dossier à partir des description files).

**Comment by Sherman-1** [comment]
Ouais c'est une bonne idée. De toutes façons il faudra fournir pour le rendu final quelque chose qui comprend un script .sh qui build les images de façon autonome donc autant le faire dès maintenant

**Comment by Sherman-1** [comment]
Toujours d'actualité, penser à rename le dossier container en " definition files "  ou quelque chose du genre avant le rendu
